- name: Update > Quality updates
  hosts: all
  tasks:
    - name: Set WindowsUpdate > DeferQualityUpdates
      ansible.windows.win_regedit:
        path: 'HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate'
        name: DeferQualityUpdates
        data: 1
        type: dword
      register: reg_result_defereupdates_1

    - name: Set WindowsUpdate > DeferQualityUpdates
      ansible.windows.win_regedit:
        path: 'HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate'
        name: DeferQualityUpdatesPeriodInDays
        data: 0
        type: dword
      register: reg_result_defereupdates_2

    - name: Set WindowsUpdate > DeferFeatureUpdates
      ansible.windows.win_regedit:
        path: 'HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate'
        name: DeferFeatureUpdates
        data: 1
        type: dword
      register: reg_result_defereupdates_3

    - name: Set WindowsUpdate > DeferFeatureUpdatesPeriodInDays
      ansible.windows.win_regedit:
        path: 'HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate'
        name: DeferFeatureUpdatesPeriodInDays
        data: 180
        type: dword
      register: reg_result_defereupdates_4

    - name: Set WindowsUpdate > ManagePreviewBuildsPolicyValue
      ansible.windows.win_regedit:
        path: 'HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate'
        name: ManagePreviewBuildsPolicyValue
        data: 1
        type: dword
      register: reg_result_defereupdates_5

    - name: Set WindowsUpdate > ManagePreviewBuildsPolicyValue
      ansible.windows.win_regedit:
        path: 'HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU'
        name: ScheduledInstallDay
        data: 0
        type: dword
      register: reg_result_defereupdates_6

    - name: Ensure Windows Updates is enabled
      ansible.windows.win_regedit:
        path: 'HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU'
        name: NoAutoUpdate
        data: 0
        type: dword
      register: reg_result_defereupdates_7

    - name: EnsureNoAutoRebootWithLoggedOnUsers is enabled
      ansible.windows.win_regedit:
        path: 'HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU'
        name: NoAutoRebootWithLoggedOnUsers
        data: 0
        type: dword
      register: reg_result_defereupdates_8

# Verification changes are applied

    - name: Ensure the registry key was corrected
      ansible.builtin.debug:
        msg: "Reg Key updates: {{ reg_result_defereupdates_1 }}"

    - name: Ensure the registry key was corrected
      ansible.builtin.debug:
        msg: "Reg Key updates: {{ reg_result_defereupdates_2 }}"

    - name: Ensure the registry key was corrected
      ansible.builtin.debug:
        msg: "Reg Key updates: {{ reg_result_defereupdates_3 }}"

    - name: Ensure the registry key was corrected
      ansible.builtin.debug:
        msg: "Reg Key updates: {{ reg_result_defereupdates_4 }}"

    - name: Ensure the registry key was corrected
      ansible.builtin.debug:
        msg: "Reg Key updates: {{ reg_result_defereupdates_5 }}"

    - name: Ensure the registry key was corrected
      ansible.builtin.debug:
        msg: "Reg Key updates: {{ reg_result_defereupdates_6 }}"

    - name: Ensure the registry key was corrected
      ansible.builtin.debug:
        msg: "Reg Key updates: {{ reg_result_defereupdates_7 }}"

    - name: Ensure the registry key was corrected
      ansible.builtin.debug:
        msg: "Reg Key updates: {{ reg_result_defereupdates_8 }}"
